/*
 * Aplikasi Pendataan Mahasiswa
 * Universitas Bina Sarana Informatika
 */
package aplikasi;

import javax.swing.JOptionPane;

/**
 *
 * @author Developer
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        usernamePanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordPanel = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        statusLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        keluarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        setTitle("Login - Sistem Pendataan Mahasiswa");
        setResizable(false);
        setSize(420, 380);

        mainPanel.setLayout(new java.awt.BorderLayout());

        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));
        headerPanel.setBackground(new java.awt.Color(70, 130, 180));
        headerPanel.setPreferredSize(new java.awt.Dimension(0, 70));

        titleLabel.setFont(new java.awt.Font("Arial", 1, 16));
        titleLabel.setText("Sistem Pendataan Mahasiswa");
        titleLabel.setForeground(java.awt.Color.WHITE);
        headerPanel.add(titleLabel);

        mainPanel.add(headerPanel, java.awt.BorderLayout.NORTH);

        formPanel.setLayout(new javax.swing.BoxLayout(formPanel, javax.swing.BoxLayout.Y_AXIS));
        formPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 20, 10, 20));

        usernamePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        usernameLabel.setText("Username:");
        usernameLabel.setPreferredSize(new java.awt.Dimension(90, 20));
        usernamePanel.add(usernameLabel);

        usernameField.setPreferredSize(new java.awt.Dimension(220, 30));
        usernamePanel.add(usernameField);
        formPanel.add(usernamePanel);

        passwordPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        passwordLabel.setText("Password:");
        passwordLabel.setPreferredSize(new java.awt.Dimension(90, 20));
        passwordPanel.add(passwordLabel);

        passwordField.setPreferredSize(new java.awt.Dimension(220, 30));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        passwordPanel.add(passwordField);
        formPanel.add(passwordPanel);

        statusLabel.setForeground(java.awt.Color.RED);
        statusLabel.setText(" ");
        statusLabel.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
        formPanel.add(statusLabel);

        infoLabel.setFont(new java.awt.Font("Arial", 2, 11));
        infoLabel.setForeground(java.awt.Color.GRAY);
        infoLabel.setText("Default: admin/admin123 (Admin) atau user/user123 (User)");
        infoLabel.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
        formPanel.add(infoLabel);

        mainPanel.add(formPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));
        buttonPanel.setPreferredSize(new java.awt.Dimension(0, 60));

        loginButton.setText("Login");
        loginButton.setPreferredSize(new java.awt.Dimension(120, 40));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(loginButton);

        keluarButton.setText("Keluar");
        keluarButton.setPreferredSize(new java.awt.Dimension(120, 40));
        keluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(keluarButton);

        mainPanel.add(buttonPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {
        loginButtonActionPerformed(evt);
    }

    /**
     * Event handler tombol Login. Mengecek username & password ke database,
     * lalu membuka MainForm (user) atau AdminForm (admin) sesuai role.
     */
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String username = usernameField.getText().trim();
        String password = new String(passwordField.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            statusLabel.setText("Username dan password harus diisi!");
            return;
        }

        try {
            java.util.Map<String, Object> row = DatabaseHelper.findUserByUsername(username);
            if (row != null) {
                String storedHash = String.valueOf(row.get("password"));
                String role = String.valueOf(row.get("role"));
                String namaLengkap = String.valueOf(row.get("nama_lengkap"));

                if (PasswordUtil.verify(password, storedHash)) {
                    DatabaseHelper.logActivity(username, "Login ke sistem sebagai " + role);
                    this.dispose();

                    if ("admin".equalsIgnoreCase(role)) {
                        new AdminForm(username, namaLengkap).setVisible(true);
                    } else {
                        new MainForm(username, namaLengkap).setVisible(true);
                    }
                } else {
                    statusLabel.setText("Password salah!");
                    passwordField.setText("");
                }
            } else {
                statusLabel.setText("Username tidak ditemukan!");
            }
        } catch (DbException e) {
            JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan database:\n" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Event handler tombol Keluar
     */
    private void keluarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin keluar dari aplikasi?",
                "Konfirmasi Keluar",
                JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }

        // Siapkan database & tabel sebelum aplikasi dibuka
        DatabaseHelper.initDatabase();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton keluarButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JPanel usernamePanel;
    // End of variables declaration//GEN-END:variables
}
