/*
 * Aplikasi Pendataan Mahasiswa
 * Universitas Bina Sarana Informatika
 */
package aplikasi;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Developer
 */
public class MainForm extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    private int selectedRow = -1;
    private String originalNim = null;

    private final String loggedInUsername;
    private final String loggedInNamaLengkap;

    /**
     * Creates new form MainForm
     */
    public MainForm(String username, String namaLengkap) {
        this.loggedInUsername = username;
        this.loggedInNamaLengkap = (namaLengkap == null || namaLengkap.isEmpty()) ? username : namaLengkap;
        initComponents();
        setupTable();
        welcomeLabel.setText("Selamat datang, " + this.loggedInNamaLengkap + " (User)");
        loadDataFromDatabase();
        this.setLocationRelativeTo(null);
        startAutoRefresh();
        RealtimeClient.getInstance().subscribe("mahasiswa", this::refreshIfNotEditing);
    }

    /**
     * Dipanggil otomatis oleh RealtimeClient begitu ada perubahan data
     * mahasiswa dari komputer manapun (termasuk aplikasi ini sendiri di
     * sesi lain). Baris yang sedang diedit sengaja dilewati supaya tidak
     * mengganggu saat pengguna sedang mengetik di form input.
     */
    private void refreshIfNotEditing() {
        if (selectedRow == -1) {
            loadDataFromDatabase();
        }
    }

    /**
     * Timer cadangan: realtime lewat WebSocket (lihat RealtimeClient) sudah
     * membuat perubahan data langsung muncul tanpa menunggu timer ini.
     * Timer ini tetap dijalankan dengan interval yang lebih longgar sebagai
     * jaring pengaman, kalau-kalau koneksi realtime sedang putus (misal
     * internet sempat bermasalah).
     */
    private void startAutoRefresh() {
        javax.swing.Timer refreshTimer = new javax.swing.Timer(20000, e -> refreshIfNotEditing());
        refreshTimer.start();
    }

    /**
     * Setup table model dengan kolom-kolom
     */
    private void setupTable() {
        tableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableModel.addColumn("NIM");
        tableModel.addColumn("Nama Lengkap");
        tableModel.addColumn("Program Studi");
        tabelMahasiswa.setModel(tableModel);
    }

    /**
     * Memuat seluruh data mahasiswa dari database ke tabel
     */
    private void loadDataFromDatabase() {
        tableModel.setRowCount(0);
        try {
            List<Map<String, Object>> rows = DatabaseHelper.getAllMahasiswa();
            for (Map<String, Object> row : rows) {
                tableModel.addRow(new Object[]{row.get("nim"), row.get("nama"), row.get("prodi")});
            }
        } catch (DbException e) {
            JOptionPane.showMessageDialog(this,
                    "Gagal memuat data:\n" + e.getMessage(),
                    "Error Database",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        nimPanel = new javax.swing.JPanel();
        nimLabel = new javax.swing.JLabel();
        nimField = new javax.swing.JTextField();
        namaPanel = new javax.swing.JPanel();
        namaLabel = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        prodiPanel = new javax.swing.JPanel();
        prodiLabel = new javax.swing.JLabel();
        prodiField = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        tambahButton = new javax.swing.JButton();
        ubahButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        bersihkanButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        tabelMahasiswa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        setTitle("Sistem Pendataan Mahasiswa");
        setResizable(true);
        setSize(900, 600);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        mainPanel.setLayout(new java.awt.BorderLayout());

        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        headerPanel.setBackground(new java.awt.Color(70, 130, 180));
        headerPanel.setPreferredSize(new java.awt.Dimension(0, 60));

        titleLabel.setFont(new java.awt.Font("Arial", 1, 18));
        titleLabel.setText("Sistem Pendataan - Universitas Bina Sarana Informatika");
        titleLabel.setForeground(java.awt.Color.WHITE);
        headerPanel.add(titleLabel);

        welcomeLabel.setFont(new java.awt.Font("Arial", 2, 12));
        welcomeLabel.setText("Selamat datang");
        welcomeLabel.setForeground(java.awt.Color.WHITE);
        headerPanel.add(welcomeLabel);

        mainPanel.add(headerPanel, java.awt.BorderLayout.NORTH);

        inputPanel.setLayout(new javax.swing.BoxLayout(inputPanel, javax.swing.BoxLayout.Y_AXIS));
        inputPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        nimPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        nimLabel.setText("NIM:");
        nimLabel.setPreferredSize(new java.awt.Dimension(100, 20));
        nimPanel.add(nimLabel);

        nimField.setPreferredSize(new java.awt.Dimension(200, 30));
        nimPanel.add(nimField);
        inputPanel.add(nimPanel);

        namaPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        namaLabel.setText("Nama Lengkap:");
        namaLabel.setPreferredSize(new java.awt.Dimension(100, 20));
        namaPanel.add(namaLabel);

        namaField.setPreferredSize(new java.awt.Dimension(200, 30));
        namaPanel.add(namaField);
        inputPanel.add(namaPanel);

        prodiPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        prodiLabel.setText("Program Studi:");
        prodiLabel.setPreferredSize(new java.awt.Dimension(100, 20));
        prodiPanel.add(prodiLabel);

        prodiField.setPreferredSize(new java.awt.Dimension(200, 30));
        prodiPanel.add(prodiField);
        inputPanel.add(prodiPanel);

        mainPanel.add(inputPanel, java.awt.BorderLayout.NORTH);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        buttonPanel.setPreferredSize(new java.awt.Dimension(0, 60));

        tambahButton.setText("Tambah");
        tambahButton.setPreferredSize(new java.awt.Dimension(100, 40));
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(tambahButton);

        ubahButton.setText("Ubah");
        ubahButton.setPreferredSize(new java.awt.Dimension(100, 40));
        ubahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(ubahButton);

        hapusButton.setText("Hapus");
        hapusButton.setPreferredSize(new java.awt.Dimension(100, 40));
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(hapusButton);

        bersihkanButton.setText("Bersihkan");
        bersihkanButton.setPreferredSize(new java.awt.Dimension(100, 40));
        bersihkanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(bersihkanButton);

        logoutButton.setText("Logout");
        logoutButton.setPreferredSize(new java.awt.Dimension(100, 40));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(logoutButton);

        mainPanel.add(buttonPanel, java.awt.BorderLayout.SOUTH);

        scrollPane.setViewportView(tabelMahasiswa);

        tabelMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMahasiswaMouseClicked(evt);
            }
        });

        mainPanel.add(scrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event handler tombol Tambah
     */
    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String nim = nimField.getText().trim();
        String nama = namaField.getText().trim();
        String prodi = prodiField.getText().trim();

        if (nim.isEmpty() || nama.isEmpty() || prodi.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Semua data harus diisi!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            DatabaseHelper.insertMahasiswa(nim, nama, prodi);
            DatabaseHelper.logActivity(loggedInUsername, "Menambah data mahasiswa NIM " + nim);
            loadDataFromDatabase();
            clearFields();
            JOptionPane.showMessageDialog(this,
                    "Data mahasiswa berhasil ditambahkan!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (DbException e) {
            if (e.isDuplicate()) {
                JOptionPane.showMessageDialog(this,
                        "NIM sudah terdaftar!",
                        "Peringatan",
                        JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Gagal menambah data:\n" + e.getMessage(),
                        "Error Database",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * Event handler tombol Ubah
     */
    private void ubahButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (selectedRow == -1 || originalNim == null) {
            JOptionPane.showMessageDialog(this,
                    "Pilih data di tabel terlebih dahulu!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nim = nimField.getText().trim();
        String nama = namaField.getText().trim();
        String prodi = prodiField.getText().trim();

        if (nim.isEmpty() || nama.isEmpty() || prodi.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Semua data harus diisi!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            DatabaseHelper.updateMahasiswa(originalNim, nim, nama, prodi);
            DatabaseHelper.logActivity(loggedInUsername, "Mengubah data mahasiswa NIM " + originalNim);
            loadDataFromDatabase();
            clearFields();
            selectedRow = -1;
            originalNim = null;
            JOptionPane.showMessageDialog(this,
                    "Data mahasiswa berhasil diubah!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (DbException e) {
            JOptionPane.showMessageDialog(this,
                    "Gagal mengubah data:\n" + e.getMessage(),
                    "Error Database",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Event handler tombol Hapus
     */
    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (selectedRow == -1 || originalNim == null) {
            JOptionPane.showMessageDialog(this,
                    "Pilih data di tabel terlebih dahulu!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin menghapus data ini?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                DatabaseHelper.deleteMahasiswa(originalNim);
                DatabaseHelper.logActivity(loggedInUsername, "Menghapus data mahasiswa NIM " + originalNim);
                loadDataFromDatabase();
                clearFields();
                selectedRow = -1;
                originalNim = null;
                JOptionPane.showMessageDialog(this,
                        "Data mahasiswa berhasil dihapus!",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (DbException e) {
                JOptionPane.showMessageDialog(this,
                        "Gagal menghapus data:\n" + e.getMessage(),
                        "Error Database",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * Event handler tombol Bersihkan
     */
    private void bersihkanButtonActionPerformed(java.awt.event.ActionEvent evt) {
        clearFields();
        selectedRow = -1;
        originalNim = null;
    }

    /**
     * Event handler tombol Logout
     */
    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin logout?",
                "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            DatabaseHelper.logActivity(loggedInUsername, "Logout dari sistem");
            RealtimeClient.getInstance().shutdown();
            this.dispose();
            new LoginForm().setVisible(true);
        }
    }

    /**
     * Event handler klik mouse pada tabel
     */
    private void tabelMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {
        selectedRow = tabelMahasiswa.getSelectedRow();
        if (selectedRow != -1) {
            originalNim = tableModel.getValueAt(selectedRow, 0).toString();
            nimField.setText(tableModel.getValueAt(selectedRow, 0).toString());
            namaField.setText(tableModel.getValueAt(selectedRow, 1).toString());
            prodiField.setText(tableModel.getValueAt(selectedRow, 2).toString());
        }
    }

    /**
     * Fungsi untuk menghapus isi semua field input
     */
    private void clearFields() {
        nimField.setText("");
        namaField.setText("");
        prodiField.setText("");
    }

    /**
     * Exit form
     */
    private void exitForm(java.awt.event.WindowEvent evt) {
        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bersihkanButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JPanel namaPanel;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JPanel nimPanel;
    private javax.swing.JTextField nimField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel prodiLabel;
    private javax.swing.JPanel prodiPanel;
    private javax.swing.JTextField prodiField;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tabelMahasiswa;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JButton tambahButton;
    private javax.swing.JButton ubahButton;
    // End of variables declaration//GEN-END:variables
}
